the total search node is 11505
result***********************************************
literal: 1	value: False
literal: 2	value: False
literal: 3	value: True
literal: 4	value: False
literal: 5	value: False
literal: 6	value: False
literal: 7	value: False
literal: 8	value: False
literal: 9	value: False
literal: 10	value: False
literal: 11	value: False
literal: 12	value: False
literal: 13	value: False
literal: 14	value: False
literal: 15	value: False
literal: 16	value: False
literal: 17	value: False
literal: 18	value: False
literal: 19	value: True
literal: 20	value: False
literal: 21	value: False
literal: 22	value: False
literal: 23	value: False
literal: 24	value: False
literal: 25	value: True
literal: 26	value: False
literal: 27	value: False
literal: 28	value: False
literal: 29	value: False
literal: 30	value: False
literal: 31	value: False
literal: 32	value: False
literal: 33	value: False
literal: 34	value: False
literal: 35	value: False
literal: 36	value: False
literal: 37	value: False
literal: 38	value: True
literal: 39	value: False
literal: 40	value: False
literal: 41	value: True
literal: 42	value: False
literal: 43	value: False
literal: 44	value: False
literal: 45	value: False
literal: 46	value: False
literal: 47	value: False
literal: 48	value: False
literal: 49	value: False
literal: 50	value: False
literal: 51	value: False
literal: 52	value: False
literal: 53	value: False
literal: 54	value: False
literal: 55	value: False
literal: 56	value: False
literal: 57	value: False
literal: 58	value: False
literal: 59	value: False
literal: 60	value: True
literal: 61	value: False
literal: 62	value: True
literal: 63	value: False
literal: 64	value: False
literal: 65	value: False
literal: 66	value: False
literal: 67	value: False
literal: 68	value: False
literal: 69	value: False
literal: 70	value: False
literal: 71	value: False
literal: 72	value: False
literal: 73	value: False
literal: 74	value: False
literal: 75	value: False
literal: 76	value: False
literal: 77	value: True
literal: 78	value: False
literal: 79	value: False
literal: 80	value: False
literal: 81	value: False
literal: 82	value: False
literal: 83	value: False
literal: 84	value: False
literal: 85	value: False
literal: 86	value: True
literal: 87	value: False
literal: 88	value: False
literal: 89	value: False
literal: 90	value: False
literal: 91	value: False
literal: 92	value: False
literal: 93	value: False
literal: 94	value: True
literal: 95	value: False
literal: 96	value: False
literal: 97	value: False
literal: 98	value: False
literal: 99	value: False
literal: 100	value: False
literal: 101	value: False
literal: 102	value: False
literal: 103	value: False
literal: 104	value: False
literal: 105	value: False
literal: 106	value: True
literal: 107	value: False
literal: 108	value: False
literal: 109	value: False
literal: 110	value: False
literal: 111	value: False
literal: 112	value: False
literal: 113	value: True
literal: 114	value: False
literal: 115	value: False
literal: 116	value: False
literal: 117	value: False
literal: 118	value: False
literal: 119	value: False
literal: 120	value: False
literal: 121	value: True
literal: 122	value: False
literal: 123	value: False
literal: 124	value: False
literal: 125	value: False
literal: 126	value: False
literal: 127	value: False
literal: 128	value: False
literal: 129	value: False
literal: 130	value: False
literal: 131	value: False
literal: 132	value: False
literal: 133	value: False
literal: 134	value: True
literal: 135	value: False
literal: 136	value: False
literal: 137	value: False
literal: 138	value: False
literal: 139	value: False
literal: 140	value: False
literal: 141	value: False
literal: 142	value: False
literal: 143	value: False
literal: 144	value: False
literal: 145	value: True
literal: 146	value: False
literal: 147	value: False
literal: 148	value: False
literal: 149	value: False
literal: 150	value: False
literal: 151	value: False
literal: 152	value: False
literal: 153	value: True
literal: 154	value: False
literal: 155	value: False
literal: 156	value: False
literal: 157	value: False
literal: 158	value: False
literal: 159	value: True
literal: 160	value: False
literal: 161	value: False
literal: 162	value: False
literal: 163	value: False
literal: 164	value: True
literal: 165	value: False
literal: 166	value: False
literal: 167	value: False
literal: 168	value: False
literal: 169	value: False
literal: 170	value: False
literal: 171	value: False
literal: 172	value: False
literal: 173	value: False
literal: 174	value: True
literal: 175	value: False
literal: 176	value: False
literal: 177	value: False
literal: 178	value: False
literal: 179	value: False
literal: 180	value: False
literal: 181	value: False
t:134.490472s