result***********************************************
literal: 1	value: True
literal: 2	value: True
literal: 3	value: unassigned
literal: 4	value: True
literal: 5	value: unassigned
literal: 6	value: True
literal: 7	value: unassigned
literal: 8	value: False
literal: 9	value: True
literal: 10	value: True
literal: 11	value: True
literal: 12	value: unassigned
literal: 13	value: False
literal: 14	value: unassigned
literal: 15	value: unassigned
literal: 16	value: unassigned
literal: 17	value: True
literal: 18	value: True
literal: 19	value: True
literal: 20	value: unassigned
literal: 21	value: True
literal: 22	value: True
literal: 23	value: False
literal: 24	value: unassigned
literal: 25	value: unassigned
literal: 26	value: unassigned
literal: 27	value: unassigned
literal: 28	value: False
literal: 29	value: unassigned
literal: 30	value: True
literal: 31	value: unassigned
literal: 32	value: False
literal: 33	value: unassigned
literal: 34	value: unassigned
literal: 35	value: False
literal: 36	value: True
literal: 37	value: True
literal: 38	value: unassigned
literal: 39	value: unassigned
literal: 40	value: True
literal: 41	value: False
literal: 42	value: True
literal: 43	value: unassigned
literal: 44	value: True
literal: 45	value: False
literal: 46	value: True
literal: 47	value: unassigned
literal: 48	value: False
literal: 49	value: unassigned
literal: 50	value: True
literal: 51	value: True
literal: 52	value: True
literal: 53	value: unassigned
literal: 54	value: unassigned
literal: 55	value: False
literal: 56	value: unassigned
literal: 57	value: unassigned
literal: 58	value: True
literal: 59	value: unassigned
literal: 60	value: True
literal: 61	value: unassigned
literal: 62	value: False
literal: 63	value: unassigned
literal: 64	value: False
literal: 65	value: True
literal: 66	value: True
literal: 67	value: True
literal: 68	value: True
literal: 69	value: True
literal: 70	value: True
literal: 71	value: unassigned
literal: 72	value: unassigned
literal: 73	value: True
literal: 74	value: unassigned
literal: 75	value: True
literal: 76	value: True
literal: 77	value: unassigned
literal: 78	value: unassigned
literal: 79	value: True
literal: 80	value: unassigned
literal: 81	value: True
literal: 82	value: unassigned
literal: 83	value: False
literal: 84	value: True
literal: 85	value: unassigned
literal: 86	value: True
literal: 87	value: unassigned
literal: 88	value: False
literal: 89	value: unassigned
literal: 90	value: unassigned
literal: 91	value: True
literal: 92	value: True
literal: 93	value: unassigned
literal: 94	value: unassigned
literal: 95	value: unassigned
literal: 96	value: False
literal: 97	value: unassigned
literal: 98	value: False
literal: 99	value: unassigned
literal: 100	value: True
literal: 101	value: unassigned
literal: 102	value: unassigned
literal: 103	value: unassigned
literal: 104	value: True
literal: 105	value: unassigned
literal: 106	value: unassigned
literal: 107	value: True
literal: 108	value: unassigned
literal: 109	value: unassigned
literal: 110	value: False
literal: 111	value: unassigned
literal: 112	value: True
literal: 113	value: True
literal: 114	value: True
literal: 115	value: unassigned
literal: 116	value: unassigned
literal: 117	value: unassigned
literal: 118	value: False
literal: 119	value: False
literal: 120	value: unassigned
literal: 121	value: True
literal: 122	value: unassigned
literal: 123	value: unassigned
literal: 124	value: unassigned
literal: 125	value: False
literal: 126	value: unassigned
literal: 127	value: unassigned
literal: 128	value: unassigned
literal: 129	value: unassigned
literal: 130	value: unassigned
literal: 131	value: unassigned
literal: 132	value: unassigned
literal: 133	value: unassigned
literal: 134	value: True
literal: 135	value: unassigned
literal: 136	value: True
literal: 137	value: True
literal: 138	value: True
literal: 139	value: unassigned
literal: 140	value: unassigned
literal: 141	value: unassigned
literal: 142	value: unassigned
literal: 143	value: unassigned
literal: 144	value: unassigned
literal: 145	value: unassigned
literal: 146	value: unassigned
literal: 147	value: unassigned
literal: 148	value: unassigned
literal: 149	value: True
literal: 150	value: unassigned
literal: 151	value: unassigned
literal: 152	value: True
literal: 153	value: unassigned
literal: 154	value: unassigned
literal: 155	value: False
literal: 156	value: unassigned
literal: 157	value: unassigned
literal: 158	value: False
literal: 159	value: unassigned
literal: 160	value: unassigned
literal: 161	value: unassigned
literal: 162	value: unassigned
literal: 163	value: True
literal: 164	value: unassigned
literal: 165	value: unassigned
literal: 166	value: unassigned
literal: 167	value: True
literal: 168	value: True
literal: 169	value: False
literal: 170	value: True
literal: 171	value: unassigned
literal: 172	value: unassigned
literal: 173	value: unassigned
literal: 174	value: True
literal: 175	value: True
literal: 176	value: True
literal: 177	value: unassigned
literal: 178	value: unassigned
literal: 179	value: unassigned
literal: 180	value: True
literal: 181	value: unassigned
literal: 182	value: unassigned
literal: 183	value: unassigned
literal: 184	value: unassigned
literal: 185	value: True
literal: 186	value: unassigned
literal: 187	value: True
literal: 188	value: unassigned
literal: 189	value: False
literal: 190	value: unassigned
literal: 191	value: unassigned
literal: 192	value: True
literal: 193	value: unassigned
literal: 194	value: unassigned
literal: 195	value: unassigned
literal: 196	value: unassigned
literal: 197	value: unassigned
literal: 198	value: True
literal: 199	value: False
literal: 200	value: unassigned
t:0.713868s